DROP TABLE USERS CASCADE CONSTRAINTS;
CREATE TABLE USERS(
  ID NUMBER(12) PRIMARY KEY,
  NAME VARCHAR2(20) NOT NULL,
  PASSWORD VARCHAR2(20) NOT NULL
);

DROP TABLE PRIORITIES CASCADE CONSTRAINTS;
CREATE TABLE PRIORITIES(
  ID NUMBER(1) PRIMARY KEY
);

DROP TABLE TASKS CASCADE CONSTRAINTS;
CREATE TABLE TASKS(
  ID NUMBER(15) PRIMARY KEY,
  USER NUMBER(12) NOT NULL REFERENCES USERS(USER_ID),
  PRIORITY NUMBER(1) REFERENCES PRIORITIES(PRIORITY_ID),
  NAME VARCHAR2(30) NOT NULL,
  TIME DATE,
  DESCRIPTION VARCHAR2(200)
);

INSERT INTO PRIORITIES VALUES (1);
INSERT INTO PRIORITIES VALUES (2);
INSERT INTO PRIORITIES VALUES (3);
INSERT INTO PRIORITIES VALUES (4);
INSERT INTO PRIORITIES VALUES (5);

DROP SEQUENCE USERS_ID_SEQUENCE;
DROP SEQUENCE TASKS_ID_SEQUENCE;
CREATE SEQUENCE USERS_ID_SEQUENCE;
CREATE SEQUENCE TASKS_ID_SEQUENCE;

DROP TRIGGER USERS_ID_TRIGGER;
CREATE TRIGGER USERS_ID_TRIGGER
BEFORE INSERT ON USERS
FOR EACH ROW
  DECLARE
  BEGIN
    SELECT USERS_ID_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
  END USERS_ID_TRIGGER;
/

DROP TRIGGER TASKS_ID_TRIGGER;
CREATE TRIGGER TASKS_ID_TRIGGER
BEFORE INSERT ON TASKS
FOR EACH ROW
  DECLARE
  BEGIN
    SELECT TASKS_ID_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
  END TASKS_ID_TRIGGER;
/